name: HgBot
on:
  schedule:
    - cron: '0 */150 * * *' # run every 150 minutes
jobs:
  check_server:
    name: Check server status
    runs-on: ubuntu-latest
    steps:
    - name: Check server status
      run: |
        systemctl www.google.com
