name: HgBot

on:
  schedule:
    - cron: '0 0/69 * * *'
jobs:
  check_server:
    name: Check server status
    runs-on: ubuntu-latest

    steps:
      - name: Check server status
        run: |
          ping opera.com
