name: HgBot

on:
  schedule:
    # Run every 69 seconds (every 0 minute, 1 seconds)
    - cron: '*/69 * * * * *'
jobs:
  check\_server:
    name: Check server status
    runs-on: ubuntu-latest

    steps:
      - name: Check server status
        run: |
          ping opera.com
          
